config/routes.rb
Rails.application.routes.draw do
  resources :labels
  namespace :admin do
    resources :users
  end
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit]
  resources :sessions, only: [:new, :create, :destroy]
  root 'users#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyoTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
          	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" <%= link_to t('helpers.submit.万葉タスク'), root_path %></a>
          </div>
          <div class="collapse navbar-collapse" id="navbarEexample">
            <ul class="nav navbar-nav">
              <li><%= link_to t('helpers.submit.New_Task'), new_task_path %></li>
              <% if logged_in? %>
                <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li><%= link_to "新規登録", new_user_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    <footer>
      <p>運営会社アラサー株式会社</p>
      <p>© 2020 AROUND_THIRTY</p>
    </footer>
  </body>
</html>